name: htop-snap
version: 2.1.0
summary: Interactive processes viewer
description: |
  Htop is an ncurses-based process viewer similar to top, but it
  allows one to scroll the list vertically and horizontally to see
  all processes and their full command lines.

  Tasks related to processes (killing, renicing) can be done without
  entering their PIDs.

grade: devel
confinement: classic

apps:
  htop:
    command: bin/htop
    plugs: [system-observe, process-control]

parts:
  htop:
    plugin: autotools
    source: https://github.com/hishamhm/htop
    source-type: git
    source-tag: 2.1.0
    build-packages: [libncursesw5-dev, pkg-config]
