name: htop
base: core20
adopt-info: htop
summary: Interactive processes viewer
description: |
  htop is an ncurses-based process viewer similar to top, but it
  allows one to scroll the list vertically and horizontally to see
  all processes and their full command lines. Tasks related to
  processes (killing, renicing) can be done without entering their PIDs.

  Once installed, this snap can _optionally_ be connected to some extra plugs:

     sudo snap connect htop:mount-observe
     sudo snap connect htop:network-control  # optional, for DELAYACCT support`

  Main website: https://htop.dev/

icon: htop.png
grade: devel
confinement: strict
license: GPL-2.0
compression: lzo

apps:
  htop:
    command-chain: [bin/locales-launch]
    command: usr/local/bin/htop
    desktop: usr/local/share/applications/htop.desktop
    environment:
      TERMINFO_DIRS: $SNAP/lib/terminfo:$SNAP/usr/share/terminfo
    plugs:
      - hardware-observe
      - mount-observe
      - network-control
      - process-control
      - system-observe

parts:
  htop:
    plugin: autotools
    source: https://github.com/htop-dev/htop
    source-type: git
    source-branch: master
    autotools-configure-parameters:
      - --enable-delayacct
      - --enable-linux-affinity
      - --enable-openvz
      - --enable-unicode
      - --enable-vserver
      - --with-sensors
    override-build: |
      sed -i 's|Icon=htop|Icon=/usr/local/share/pixmaps/htop.png|' htop.desktop
      snapcraftctl set-version $(git describe --tags --long)
      snapcraftctl build
    build-packages:
      - libncursesw5-dev
      - libnl-3-dev
      - libnl-genl-3-dev
      - libsensors4-dev
      - pkg-config
    stage-packages:
      - kitty-terminfo
      - libncursesw5
      - libsensors5
      - libtinfo5
      - libsystemd0
      - ncurses-base
      - ncurses-term
      - lsof
      - strace

  # Stage snap for fixing the Glibc locales
  # https://forum.snapcraft.io/t/the-locales-launch-stage-snap/10296
  locales-launch:
    source: https://github.com/Lin-Buo-Ren/locales-launch.git
    source-tag: v1.0.0
    plugin: dump
    stage-packages:
    # For localedef(1)
    - libc-bin
    # For locale data used by localedef(1)
    - locales
    # All pre-generated locale data
    # DISABLED: Lots of duplicate data will be included in snap when this is staged, unless the target machine has no resource to generate them in runtime otherwise not using it
    #
    #   Lack of compiled locales breaks gettext based localisation - snapcraft - snapcraft.io
    #   https://forum.snapcraft.io/t/lack-of-compiled-locales-breaks-gettext-based-localisation/3758
    #
    #- locales-all
    stage:
      - bin/locales-launch
      - etc/locale.alias
      - usr/bin/localedef
      - usr/share/doc/locales
      - usr/share/i18n
      - usr/share/locale
